### ISSUE TITLE
could  you  please  tell  me   about     how  to  use  this  project ?

### ISSUE THREAD

**Issue by heartInsert** [mlisi1/anymal_c_gazebo_sim#1]
Hi , mate  ,  I  know  basic  ros  command ,  but your  project   structure  is a  little  different from  official  demo ,  should  I  put  this   whole  project  into    catkin_ws/src  ?  And  run    `catkin_make` .

**Comment by mlisi1** [comment]
> Hi , mate , I know basic ros command , but your project structure is a little different from official demo , should I put this whole project into catkin_ws/src ? And run `catkin_make` .

Hello there,
as you're using `catkin_make` i'm assuming you're using ros1, but this project uses ros2, specifically the humble distro, that's why the project structure is different.
I'm sorry i haven't made a readme yet to make the usage clear.

**Comment by heartInsert** [comment]
OK ,  I  get  it ,  thank  you.
